modify pre commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,25 +1,25 @@
 #!/bin/bash
-. "$(dirname "$0")/_/husky.sh"
+# . "$(dirname "$0")/_/husky.sh"
 
 STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|vue)$')
 
-if [[ "$STAGED_FILES" = "" ]]; then
-  echo "No staged files."
-  exit 0
-fi
+# if [[ "$STAGED_FILES" = "" ]]; then
+#   echo "No staged files."
+#   exit 0
+# fi
 
 #npm run prettier-format
 # npx prettier --config .prettierrc 'src/**/*.{js,vue}' --write 
 
 for FILE in $STAGED_FILES
 do
-#   eslint "$FILE"
-  npx prettier --config .prettierrc "$FILE" --write
+  eslint "$FILE"
+  npx prettier --config .prettierrc $FILE --write
 
-  if [[ "$?" == 0 ]]; then
-    echo "\t\033[32mESLint Passed: $FILE\033[0m"
-  else
-    echo "\t\033[41mESLint Failed: $FILE\033[0m"
-    PASS=false
-  fi
+#   if [[ "$?" == 0 ]]; then
+#     echo "\t\033[32mESLint Passed: $FILE\033[0m"
+#   else
+#     echo "\t\033[41mESLint Failed: $FILE\033[0m"
+#     PASS=false
+#   fi
 done
