modify pre commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -17,9 +17,18 @@ do
   npx prettier --config .prettierrc $FILE --write
 
   if [[ "$?" == 0 ]]; then
-    echo "\t\033[32mESLint Passed: $FILE\033[0m"
+    echo "\tLinting file: $FILE"
   else
-    echo "\t\033[41mESLint Failed: $FILE\033[0m"
+    echo "\tLint failed for file: $FILE"
     PASS=false
   fi
 done
+
+if ! $PASS; then
+  echo "Your commit contains files that should pass ESLint but do not. Please fix the lint errors and try again.\n"
+  exit 1
+# else
+#   echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
+fi
+
+exit $?
